#!/usr/bin/env python3
"""Generate a 2x4 montage from supplement NPZ and DA-V2 output.

Layout:
  Left | DA-V2 | D455 depth | D435 depth
  Global aligned DA-V2 | DA-V2 metric depth | DA-V2 metric linear | Stereo metric depth

Run with the reorganized supp_2 / DA-V2 / aligned-depth defaults:
  python3 Depth-Anything-V2/ml_gt_generate/tools/img_conclusion_gen.py \
    --params-yaml sml/fitted_scale_shift_0825-1_0-5_dav2_2.yaml

Test 10 samples:
  python3 Depth-Anything-V2/ml_gt_generate/tools/img_conclusion_gen.py \
    --params-yaml sml/fitted_scale_shift_0825-1_0-5_dav2_2.yaml \
    --max-files 10 --log-depth
"""

import argparse
from pathlib import Path

import cv2
import matplotlib.pyplot as plt
from matplotlib.colors import LogNorm
import numpy as np
import yaml


ML_GT_ROOT = Path(__file__).resolve().parents[1]
DATASET_DIR = ML_GT_ROOT / "dataset/train_1_0-5"


def valid_depth(depth):
    depth = np.asarray(depth, dtype=np.float32)
    return np.where(np.isfinite(depth) & (depth > 0), depth, np.nan)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--data", type=Path,
                    default=DATASET_DIR / "train_1_0-5_supp_2")
    ap.add_argument("--da-dir", type=Path,
                    default=DATASET_DIR / "train_1_0-5_dav2_2")
    ap.add_argument("--da-metric-dir", type=Path,
                    default=DATASET_DIR / "train_1_0-5_dav2_2_metric")
    ap.add_argument("--stereo-depth-dir", type=Path,
                    default=DATASET_DIR / "train_1_0-5_stereo_depth_2")
    ap.add_argument("--aligned-depth-dir", type=Path,
                    default=DATASET_DIR / "train_1_0-5_realsense_aligned_2")
    ap.add_argument("--out", "--out-dir", dest="out", type=Path,
                    default=DATASET_DIR / "out_2")
    ap.add_argument("--params-yaml", type=Path, required=True,
                    help="global scale/shift YAML generated by the separate SML project")
    ap.add_argument("--pair", default="1_0")
    ap.add_argument("--depth-min", type=float, default=0.3)
    ap.add_argument("--depth-max", type=float, default=20.0)
    ap.add_argument("--depth-cmap", default="inferno",
                    help="Matplotlib colormap for metric-depth panels")
    ap.add_argument("--da-metric-depth-max", type=float, default=0.0,
                    help="Separate DA-V2 metric maximum; 0 uses --depth-max")
    ap.add_argument("--da-metric-linear-max", type=float, default=80.0,
                    help="Linear colorbar maximum for the extra DA-V2 metric panel")
    ap.add_argument("--log-depth", action="store_true",
                    help="Use a shared logarithmic scale for metric-depth panels")
    ap.add_argument("--skip-existing", action="store_true",
                    help="Resume by skipping montage JPG files that already exist")
    ap.add_argument("--start-index", type=int, default=0,
                    help="Start index in the sorted NPZ list")
    ap.add_argument("--max-files", type=int, default=0)
    args = ap.parse_args()

    if args.log_depth and not 0 < args.depth_min < args.depth_max:
        raise SystemExit("Log depth requires 0 < --depth-min < --depth-max")
    da_metric_max = args.da_metric_depth_max or args.depth_max
    if da_metric_max <= 0 or (args.log_depth and da_metric_max <= args.depth_min):
        raise SystemExit("Invalid --da-metric-depth-max")
    if args.da_metric_linear_max <= 0:
        raise SystemExit("--da-metric-linear-max must be positive")

    with args.params_yaml.open() as f:
        params = yaml.safe_load(f)
    if args.pair not in params:
        raise SystemExit(f"Pair {args.pair!r} not found in {args.params_yaml}")
    scale = float(params[args.pair]["ransac_scale"])
    shift = float(params[args.pair]["ransac_shift"])
    files = sorted(args.data.glob("*.npz"))
    if args.start_index < 0:
        raise SystemExit("--start-index must be non-negative")
    files = files[args.start_index:]
    files = files[:args.max_files] if args.max_files else files
    if not files:
        raise SystemExit(f"No .npz files in {args.data}")
    args.out.mkdir(parents=True, exist_ok=True)

    required = {"left", "depth_d455", "depth_d435"}
    for i, path in enumerate(files):
        output = args.out / f"{path.stem}.jpg"
        if args.skip_existing and output.is_file():
            continue
        with np.load(path, allow_pickle=False) as data:
            missing = required.difference(data.files)
            if missing:
                print(f"Skip {path.stem}: missing {sorted(missing)}")
                continue
            left = data["left"]
            d455 = valid_depth(data["depth_d455"])
            d435 = valid_depth(data["depth_d435"])

        aligned_d455 = args.aligned_depth_dir / "d455" / f"{path.stem}.npy"
        aligned_d435 = args.aligned_depth_dir / "d435" / f"{path.stem}.npy"
        aligned_depth_used = aligned_d455.is_file() and aligned_d435.is_file()
        if aligned_depth_used:
            d455 = valid_depth(np.load(aligned_d455, allow_pickle=False))
            d435 = valid_depth(np.load(aligned_d435, allow_pickle=False))

        da_path = args.da_dir / f"{path.stem}.npy"
        if not da_path.is_file():
            print(f"Skip {path.stem}: missing {da_path}")
            continue
        da_metric_path = args.da_metric_dir / f"{path.stem}.npy"
        if not da_metric_path.is_file():
            print(f"Skip {path.stem}: missing {da_metric_path}")
            continue
        stereo_path = args.stereo_depth_dir / f"{path.stem}.npy"
        if not stereo_path.is_file():
            print(f"Skip {path.stem}: missing {stereo_path}")
            continue
        da_raw = np.asarray(np.load(da_path, allow_pickle=False),
                            dtype=np.float32).squeeze()
        da_metric = valid_depth(np.load(da_metric_path, allow_pickle=False)).squeeze()
        stereo_depth = valid_depth(np.load(stereo_path, allow_pickle=False))
        if da_raw.ndim != 2:
            print(f"Skip {path.stem}: DA-V2 output must be 2D, got {da_raw.shape}")
            continue
        h, w = left.shape[:2]
        if da_raw.shape != (h, w):
            da_raw = cv2.resize(da_raw, (w, h), interpolation=cv2.INTER_LINEAR)
        if da_metric.shape != (h, w):
            da_metric = cv2.resize(da_metric, (w, h), interpolation=cv2.INTER_LINEAR)
        # The comparison panel follows the shared depth range.  Keep the raw
        # metric output unchanged for the independent 0--80 m panel below.
        da_metric_clamped = np.minimum(da_metric, da_metric_max)
        da_vis = np.where(np.isfinite(da_raw) & (da_raw != 0), da_raw, np.nan)
        global_inv = np.clip(scale * da_vis + shift, 1e-3, None)
        global_depth = 1.0 / global_inv
        depth_style = (
            {"cmap": args.depth_cmap, "norm": LogNorm(vmin=args.depth_min,
                                                        vmax=args.depth_max)}
            if args.log_depth
            else {"cmap": args.depth_cmap, "vmin": 0, "vmax": args.depth_max}
        )
        da_metric_style = (
            {"cmap": args.depth_cmap, "norm": LogNorm(vmin=args.depth_min,
                                                        vmax=da_metric_max)}
            if args.log_depth
            else {"cmap": args.depth_cmap, "vmin": 0, "vmax": da_metric_max}
        )

        fig, ax = plt.subplots(2, 4, figsize=(16, 8), constrained_layout=True)
        ax[0, 0].imshow(cv2.cvtColor(left, cv2.COLOR_BGR2RGB))
        ax[0, 0].set_title("Stereo left")
        im_da = ax[0, 1].imshow(da_vis, cmap="magma")
        ax[0, 1].set_title("DA-V2 original output")
        im_depth = ax[0, 2].imshow(d455, **depth_style)
        ax[0, 2].set_title("D455 aligned depth" if aligned_depth_used else "D455 depth")
        ax[0, 3].imshow(d435, **depth_style)
        ax[0, 3].set_title("D435 aligned depth" if aligned_depth_used else "D435 depth")
        ax[1, 0].imshow(global_depth, **depth_style)
        ax[1, 0].set_title("Global aligned DA-V2")
        im_da_metric = ax[1, 1].imshow(da_metric_clamped, **da_metric_style)
        ax[1, 1].set_title("DA-V2 metric depth")
        im_da_metric_linear = ax[1, 2].imshow(
            da_metric, cmap=args.depth_cmap, vmin=0,
            vmax=args.da_metric_linear_max,
        )
        ax[1, 2].set_title("Original output DA-V2 metric Depth")
        ax[1, 3].imshow(stereo_depth, **depth_style)
        ax[1, 3].set_title("Stereo metric depth")
        for panel in ax.flat:
            panel.axis("off")
        fig.colorbar(im_da, ax=ax[0, 1], fraction=0.046, pad=0.04,
                     label="Relative inverse depth")
        shared_depth_axes = [ax[0, 2], ax[0, 3], ax[1, 0], ax[1, 3]]
        separate_da_metric_scale = not np.isclose(da_metric_max, args.depth_max)
        if not separate_da_metric_scale:
            shared_depth_axes.append(ax[1, 1])
        fig.colorbar(im_depth, ax=shared_depth_axes,
                     fraction=0.023, pad=0.02, label="Depth (m)")
        if separate_da_metric_scale:
            fig.colorbar(im_da_metric, ax=ax[1, 1], fraction=0.046, pad=0.04,
                         label=f"DA-V2 metric depth (m), max={da_metric_max:g}")
        fig.colorbar(
            im_da_metric_linear, ax=ax[1, 2], fraction=0.046, pad=0.04,
            label=f"DA-V2 metric depth (m), linear 0–{args.da_metric_linear_max:g}",
        )
        fig.suptitle(
            f"{path.stem} | global depth = 1 / "
            f"({scale:.6g} × DA-V2 + {shift:.6g})"
        )
        fig.savefig(output, dpi=120)
        plt.close(fig)
        if i == 0 or (i + 1) % 100 == 0 or i + 1 == len(files):
            print(f"[{i + 1}/{len(files)}] {output}", flush=True)


if __name__ == "__main__":
    main()
